In [4]:
import numpy as np


In [23]:
A=np.array([[1,2,3],[-2,3,0],[5,1,4]])
B=np.array([[1,2,3],[2,4,6],[3,7,2]])
U=np.array([[-4]])
V=np.array([[3,2,10]])

In [19]:
print(A)

[[ 1  2  3]
 [-2  3  0]
 [ 5  1  4]]


In [20]:
print(B)

[[1 2 3]
 [2 4 6]
 [3 7 2]]


In [24]:
print (U)

[[-4  1  1]]
